# Generated by Django 5.0.2 on 2024-04-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
