# Generated by Django 5.0.2 on 2024-04-23 08:32

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_remove_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=userauths.models.default_image, upload_to='image'),
        ),
    ]
