# Generated by Django 5.0.2 on 2024-03-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Some clothes', max_length=100),
        ),
    ]
