# Generated by Django 5.0.2 on 2024-03-17 19:37

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', blank=True, length=4, max_length=10, prefix='sku', unique=True),
        ),
    ]
