# Generated by Django 5.0.3 on 2024-03-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_productimages_product'),
        ('core', '0010_vendor_date_alter_product_vendor'),
    ]

    operations = [
    ]
