# Generated by Django 5.0.2 on 2024-03-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_categoryimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImages',
        ),
    ]
