# Generated by Django 5.0.2 on 2024-04-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitems',
            old_name='qty',
            new_name='quantity',
        ),
    ]
