# Generated by Django 5.0.2 on 2024-04-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_cartorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='user',
        ),
    ]
