# Generated by Django 5.0.2 on 2024-04-23 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_cartorderitems_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
    ]
